name: "Deploy Test"

on:
 push:
  tags:
   - "Test/v*"

env:
 PROJECT_PATH: calculator/calculator.csproj

jobs:
 deploy:
  runs-on: windows-2022
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1 
      with:
       dotnet-version: 5.0.x
    - run: dotnet restore ${{ env.PROJECT_PATH }}  
    - run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore
    - run: dotnet publish ${{ env.PROJECT_PATH }} -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=false /p:IncludeNativeLibrariesForSelfExtract=true --no-build
    - uses: actions/create-release@v1
      id: create_release
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: ${{ github.ref }}
       release_name: ${{ github.ref }}

    - uses: csexton/release-asset-action@v2
      with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       pattern: calculator/bin/Release/net5.0-windows/win-x64/publish/*.exe
       release-url: ${{ steps.create_release.outputs.upload_url }}
  

    - uses: caphyon/advinst-github-action@v1.0
      name: Build AIP
      with:
          advinst-version: '19.3'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\Setup\Setup.aip
          aip-build-name: DefaultBuild
          aip-package-name: setup.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetProperty FOO="foo"
            SetVersion 1.2.0
    - uses: actions/upload-artifact@v2
      name: Publish setup artifact
      with:
          name: setup
          path: ${{ github.workspace }}\setup\setup.msi
