name: Build Advanced Installer Project (.AIP)
on:
 push:
  tags:
   - "Test/v*"

env:
 PROJECT_PATH: calculator/calculator.csproj
jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Build Aip Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build AIP
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-version: '19.3'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}\Setup\Setup.aip
          aip-build-name: DefaultBuild
          aip-package-name: setup.msi
          aip-output-dir:  ${{ github.workspace }}\setup
          aip-commands: |
            SetProperty FOO="foo"
            SetVersion 1.2.0
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: ${{ github.workspace }}\setup\setup.msi
          name: setup
